# Generated by Django 4.2 on 2024-07-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djfile',
            name='name',
        ),
    ]
