# Generated by Django 4.2 on 2024-08-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0004_djdatabasebackup_count_run_djdatabasebackup_last_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djfile',
            name='backup',
        ),
        migrations.AddField(
            model_name='djfilebackup',
            name='files',
            field=models.ManyToManyField(to='dj_backup.djfile'),
        ),
    ]
