# Generated by Django 4.2 on 2024-08-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0005_remove_djfile_backup_djfilebackup_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJBackUpStorageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], max_length=12)),
                ('storage_name', models.CharField(max_length=100)),
                ('backup_name', models.CharField(max_length=300)),
                ('backup_url', models.TextField(blank=True, null=True)),
                ('size', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='djdatabasebackup',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='djfilebackup',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='djdatabasebackup',
            name='unit',
            field=models.CharField(choices=[('once', 'Once'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10),
        ),
        migrations.AlterField(
            model_name='djfilebackup',
            name='unit',
            field=models.CharField(choices=[('once', 'Once'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10),
        ),
        migrations.AddField(
            model_name='djdatabasebackup',
            name='results',
            field=models.ManyToManyField(to='dj_backup.djbackupstorageresult'),
        ),
        migrations.AddField(
            model_name='djfilebackup',
            name='results',
            field=models.ManyToManyField(to='dj_backup.djbackupstorageresult'),
        ),
    ]
