# Generated by Django 4.2 on 2024-08-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0006_djbackupstorageresult_alter_djdatabasebackup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='djbackupstorageresult',
            name='storage_name',
        ),
        migrations.AddField(
            model_name='djbackupstorageresult',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj_backup.djstorage'),
        ),
    ]
