# Generated by Django 4.2 on 2024-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0007_djstorage_remove_djbackupstorageresult_storage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djstorage',
            name='display_name',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
