# Generated by Django 4.2 on 2024-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0008_djstorage_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='djbackupstorageresult',
            name='out',
            field=models.TextField(blank=True, null=True),
        ),
    ]
