# Generated by Django 4.2 on 2024-08-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0009_djbackupstorageresult_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djbackupstorageresult',
            name='backup_url',
        ),
    ]
