# Generated by Django 4.2 on 2024-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0011_alter_djdatabasebackup_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djdatabasebackup',
            name='storages',
            field=models.ManyToManyField(blank=True, to='dj_backup.djstorage'),
        ),
        migrations.AddField(
            model_name='djfilebackup',
            name='storages',
            field=models.ManyToManyField(blank=True, to='dj_backup.djstorage'),
        ),
    ]
