# Generated by Django 4.2 on 2024-08-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0012_djdatabasebackup_storages_djfilebackup_storages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djdatabasebackup',
            old_name='count_run',
            new_name='repeats',
        ),
        migrations.RenameField(
            model_name='djfilebackup',
            old_name='count_run',
            new_name='repeats',
        ),
    ]
