# Generated by Django 4.2 on 2024-08-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0013_rename_count_run_djdatabasebackup_repeats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djdatabasebackup',
            name='database',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='djdatabasebackup',
            name='files',
            field=models.ManyToManyField(to='dj_backup.djfile'),
        ),
    ]
