# Generated by Django 4.2 on 2024-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0015_alter_djdatabasebackup_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='djbackupstorageresult',
            name='backup_type',
            field=models.CharField(choices=[('file', 'File'), ('database', 'Database')], default='-', max_length=10),
            preserve_default=False,
        ),
    ]
