# Generated by Django 4.2 on 2024-08-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0016_djbackupstorageresult_backup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='djdatabasebackup',
            name='additional_args',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djdatabasebackup',
            name='database_name',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
    ]
