# Generated by Django 4.2 on 2024-08-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0018_rename_database_name_djdatabasebackup_database_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djdatabasebackup',
            name='files',
        ),
    ]
