# Generated by Django 4.2 on 2024-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0019_remove_djdatabasebackup_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='djdatabasebackup',
            name='count_run',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='djfilebackup',
            name='count_run',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
