# Generated by Django 4.2 on 2024-08-10 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0020_djdatabasebackup_count_run_djfilebackup_count_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djbackupstorageresult',
            name='backup_type',
        ),
    ]
