# Generated by Django 4.2 on 2024-08-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0024_djbackupstorageresult_temp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='djdatabasebackup',
            name='has_temp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='djfilebackup',
            name='has_temp',
            field=models.BooleanField(default=True),
        ),
    ]
