# Generated by Django 4.2 on 2024-08-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0025_djdatabasebackup_has_temp_djfilebackup_has_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djbackupstorageresult',
            name='temp_location',
        ),
    ]
