# Generated by Django 4.2 on 2024-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0026_remove_djbackupstorageresult_temp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='djbackupstorageresult',
            name='temp_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
